services:

  # Database -- PROD profile
  finance-db:
    image: postgres:15-alpine
    container_name: finance_db_prod
    restart: always
    ports:
      - "5433:5432" # external port 5433
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database -- DEV profile
  finance-db-dev:
    image: postgres:15-alpine
    # container name is the host name of pgadmin
    container_name: finance_db_dev 
    restart: always
    environment:
      POSTGRES_DB: finance_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432" # external port 5434
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data # separate volume  
    networks:
      - finance-net

  # Back-end -- PROD profile 
  finance_manager-api:
    build:
      context: ./Backend/FinanceManager-API
      dockerfile: Dockerfile
    container_name: finance_manager-api
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=finance-db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      finance-db:
        condition: service_healthy # starts only when the database is ok
    networks:
      - finance-net

 # database admin
  pgadmin:
    image: dpage/pgadmin4
    container_name: finance_pgadmin
    restart: always
    ports:
      - "5050:80" # acess in localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - finance-net
    depends_on:
      - finance-db
  
  finance_manager-web:
    build: 
      context: ./Frontend/FinanceManager-Web
      dockerfile: Dockerfile
    container_name: finance_manager-web
    restart: always
    ports:
      - "80:80" # just localhost
    networks:
      - finance-net
    depends_on:
      - finance_manager-api


volumes:
  postgres_data:
  postgres_data_dev:

networks:
  finance-net:
    driver: bridge